import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {encodeChallenge,decodeChallenge,matchScore,scoreQuiz,escapeHTML,validName} from '../js/core.js';
const read=id=>JSON.parse(fs.readFileSync(new URL(`../content/${id}.json`,import.meta.url),'utf8'));
const challenge=read('know-me');
test('Korean/emoji names and every answer round trip through fragment',()=>{for(const name of ['심심이','친구 😄','<script>']){const a=challenge.questions.map((_,i)=>i%4);assert.deepEqual(decodeChallenge(encodeChallenge(name,a),challenge.questions),{name,answers:a});}});
test('Malformed, oversized, outdated and invalid answer payloads rejected',()=>{for(const value of ['', '###','a'.repeat(2001),btoa('{}'),btoa(JSON.stringify({v:2,n:'a',a:Array(8).fill(0)})),encodeChallenge('a',Array(8).fill(99)),encodeChallenge('',Array(8).fill(0)),encodeChallenge('a',[]),encodeChallenge('a'.repeat(17),Array(8).fill(0))])assert.throws(()=>decodeChallenge(value,challenge.questions));});
test('Friend scores calculate 0, partial and perfect correctly',()=>{assert.equal(matchScore([0,1,2,3],[0,1,2,3]),100);assert.equal(matchScore([0,1,2,3],[1,2,3,0]),0);assert.equal(matchScore([0,1,2,3],[0,1,0,0]),50);assert.throws(()=>matchScore([],[]));});
test('Untrusted names escaped for rendering',()=>{assert.equal(escapeHTML('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;');assert.equal(validName('  '),false);assert.equal(validName('a'.repeat(17)),false);});
function reachableResults(d){const found=new Set(),answers=[];function walk(index){if(found.size===d.results.length)return;if(index===d.questions.length){found.add(scoreQuiz(d.questions,answers,d.results).id);return;}for(let i=0;i<d.questions[index].options.length;i++){answers[index]=i;walk(index+1);}}walk(0);return found;}
for(const id of ['group-chat','manual','fantasy-job']){
 const d=read(id);
 test(`${id}: content references and every result reachable`,()=>{const expected={"group-chat":[12,8],manual:[8,8],"fantasy-job":[9,12]}[id];assert.equal(d.questions.length,expected[0]);assert.equal(d.results.length,expected[1]);const ids=d.results.map(r=>r.id);assert.equal(new Set(ids).size,ids.length);for(const q of d.questions){assert.ok(q.text);assert.ok(q.text.length<=45);assert.ok(q.options.length>=2);for(const o of q.options){assert.ok(o.text);assert.ok(o.text.length<=28);for(const [k,v] of Object.entries(o.scores)){assert.ok(ids.includes(k));assert.ok(Number.isFinite(v));}}}for(const r of d.results){assert.ok(r.traits.length===3);assert.ok(r.code&&r.keyword&&r.character&&r.sprite?.src);assert.ok(fs.existsSync(new URL(`..${r.sprite.src.slice(1)}`,import.meta.url)));}assert.deepEqual([...reachableResults(d)].sort(),ids.sort());});
 test(`${id}: repeat scoring deterministic and incomplete answers rejected`,()=>{const a=d.questions.map(()=>0);assert.deepEqual(scoreQuiz(d.questions,a,d.results),scoreQuiz(d.questions,a,d.results));assert.throws(()=>scoreQuiz(d.questions,[],d.results));});
}
test('No third-party scripts; common social preview is wired',()=>{const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.doesNotMatch(html,/<script[^>]*src=["']https?:/);assert.match(html,/og:image[^>]+assets\/og\.png/);assert.match(html,/twitter:card[^>]+summary_large_image/);assert.ok(fs.existsSync(new URL('../assets/og.png',import.meta.url)));const pkg=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url)));assert.equal(Object.keys(pkg.dependencies||{}).length,0);});
